### ISSUE TITLE
use a plugin manager?

### ISSUE THREAD

**Issue by effusive-lazyness** [isene/hyperlist.vim#1]
I just stumbled upon hyperlist today and after reading the spec I was mind blown and wanted to try it right away with vim!
The only problem was I am using Neovim which is quite agressive when it comes to deprecated stuff and that's where I'm going at.
Why use a vimball when there are so many plugin managers that are doing a much better job at managing plugins?

**Comment by isene** [comment]
I use Vizardry myself and it works beautifully with all plugins on github. Could you try that and tell me how that works for you on nvim?

And yeah,  I should update the install section to reflect better installation ways. 

Cool that it sparked your interest.

**Comment by effusive-lazyness** [comment]
Thanks Vizardry worked like a charm!

**Comment by isene** [comment]
I added the link to Vizardry to the Readme.md and how to install the HyperList plugin. Thanks for the nudge.

**Comment by lsrdg** [comment]
From https://github.com/ardagnir/vizardry : 

> Note: I'm too busy with other stuff to work on this right now. If you like vizardry, I recommend using dbeniamine's awesome vizardry fork

I had no problem installing with [minpac](https://github.com/k-takata/minpac):

`call minpac#add('isene/hyperlist.vim')`.

Maybe just a general recommendation and a Vim Plug example (since a lot of people use [vim-plug](https://github.com/junegunn/vim-plug))?

**Comment by CantGetRight82** [comment]
I found this plugin while planning to create something similar. Nice work, i'm excited to try it!

The installation part did hold me back a little. However, it seems to install just fine with this popular plugin manager:
https://github.com/junegunn/vim-plug

**Comment by isene** [comment]
Thanks guys.

Added info on this in the Readme
