### ISSUE TITLE
question on hyperlinks

### ISSUE THREAD

**Issue by rwmitchell** [isene/hyperlist.vim#14]
I'm sure this is just confusion on my part and I'll probably do a poor job of describing my question, but here goes.

The command 'gf' when typed while over the string sequence: ```![LABEL]<path/file>```
will open the file in its preferred file handler. ie: a .png will be opened by Preview on OSX.

On GitHub to have inline images in a .md file, the format seems to need to be ```[LABEL](path/file)```
where the filename is enclosed in '()' instead of '<>'

- Is that an intentional discrepancy?

- Have I changed something to cause this difference? ( I know I changed the md-img-paste.vim plugin to match what I thought hyperlist expected )

- Am I using the wrong tool to create .md files?

Thanks!

**Comment by isene** [comment]
Yes, you are using the wrong tool to create .md files :-)
The VIM HyperList plugin is specifically for creating HyperList files (see https://isene.org/hyperlist/)

**Comment by rwmitchell** [comment]
It may be the wrong tool, but otherwise works better than the other things I've tried.

Mostly I love the folding and the ease of using the spacebar to toggle.

And I've learned using 'gx' instead of 'go' does what I want for opening images using the syntax GitHub expects.

**Comment by isene** [comment]
:-)

It's cool to learn that there's one person out there using my plugin for something entirely different than what it is designed for.
