### ISSUE TITLE
Calendar error

### ISSUE THREAD

**Issue by SenkiJun** [isene/hyperlist.vim#15]
Hey, thanks for the awesome plugin. 
I'm having issues with the Calendar. 
I installed and setup gcalcli without problems but this is what I get when I do \G.       

![image](https://github.com/user-attachments/assets/e25ee3d4-4d67-4276-b2e6-5c8b1cca06c3)

Should I add something to my .vimrc ? I just need to use the default calendar.

**Comment by isene** [comment]
Yes, you need this in your .vimrc:

let g:calendar = "you@maildomain.com"

(substituting the 'you@maildomain.com' with the e-mail for your calendar)

Tell me how that works.

**Comment by SenkiJun** [comment]
Oh it works ! Thank you so much.

One last thing;

Is it possible to opt-out adding future events only ? 
It doesn't add today's events as well even tho it's in the future clock vise.

**Comment by isene** [comment]
Good. I will look into your request here.

**Comment by isene** [comment]
It now takes todays events in by default (this is better).

Let,s do a quick-and-dirty test here. Take this [hyperlist.vim](http://isene.com/x/hyperlist.vim) and put it into your vim syntax folder (replacing the previous hyperlist.vim) and try setting this in your .vimrc:

let g:alldates=1

... and you will now have all events pushed to your calendar - even the old ones.

Let me know if this works.

**Comment by SenkiJun** [comment]
> let g:alldates=1

It works ! Thank you so much for your time.  
Not too important but one last great improvement would be "to not duplicate events if they already exist in the calendar".
Thank you so much for the method and the plugin. It changed how I work and think.

**Comment by isene** [comment]
Good to hear that it works. Will update the docs (and credit you for this change) and release a new version.

As for the "no duplicate events", that would require a download of your calendar and parsing each event to check for duplicates - too much code (and potential security issues) ta warrant it. But, if you have other requests for this plugin, please ask :)

**Comment by SenkiJun** [comment]
Thank you so much. 
I hope more people know about the method, it really simplifies everything.
It's really well thought and documented. 

(For the event duplication quick work around for me to change date syntax after I push to google calendar.
So they won't get re-uploaded after I add another event.)

![image](https://github.com/user-attachments/assets/dfaddcdf-495a-430e-bdf4-c8a1690a1943)
