### ISSUE TITLE
vim not accepting "\"

### ISSUE THREAD

**Issue by anthrolisp** [isene/hyperlist.vim#3]
I installed with the vmb file. I'm able to build a list in .hl file, but vim will not accept "\" key. My laptop just beeps at me. Any ideas? Thanks in advance!

**Comment by isene** [comment]
Thanks for trying out the plugin.
Now, when you say ' vim not accepting "\" ', is that in Normal or Insert mode?
And, do you have that key mapped to something specific in your .vimrc?
Also, try renaming your .vimrc to .vimrc.tmp and create a .hl file and check again (just to move your .vimrc file out of the way for testing this - you rename the .vimrc.tmp back to .vimrsc afterwards of course). Do this and tell me what happens :-)

**Comment by anthrolisp** [comment]
It does work, my apologies. I forgot that \ is shorthand for the leader and not referring to the actual "\" key! I'm returning to vim from many years with emacs. hyperlist.vim looks very interesting and I'm looking forward to exploring it for my workflows. Thank you!!

**Comment by isene** [comment]
You are very welcome. Glad it sorted out easily :-)
