### ISSUE TITLE
hyperlists in other document types

### ISSUE THREAD

**Issue by anthrolisp** [isene/hyperlist.vim#5]
I'm unable to get hyperlists to work in other document types. I've tried adding the following lines as per documentation for both txt and also md in the syntax folder (txt.vim and md.vim).

`syn include @HL ~/.vim/syntax/hyperlist.vim
syn region HLSnip matchgroup=Snip start="HLstart" end="HLend" contains=@HL
hi link Snip SpecialComment`

I had to create the files for both. For md, I use the vim-pandoc-syntax and even tried adding the lines to the pandoc.vim file. None of these worked.

Any ideas? Many thanks in advance!

**Comment by isene** [comment]
Hmmm... While writing a reply to your issue here, I went and checked the example in the documentation - it used to display nicely. Now it doesn't. Something is wrong. I'll look into it.

**Comment by isene** [comment]
Wait! It DOES work. Try adding those three lines to your ~/.vim/syntax/txt.vim file (and make sure hyperlist.vim is indeed located at ~/.vim/syntax/hyperlist.vim). Then open the file ~/.vim/doc/hyperlist.txt and go to line 198. You should see a correctly collapsed Hyperlist with correct highlighting.

**Comment by anthrolisp** [comment]
Thanks for your reply. I tried again, adding those three lines to my ~/.vim/syntax/txt.vim file and also made sure hyperlist.vim is located at ~/.vim/syntax/hyperlist.vim, and it sill doesn't work. There is no highlighting or folding in the embedded hyperlist in file ~/.vim/doc/hyperlist.txt . Space bar just moves the cursor one space forward. Should the ~/.vim/syntax/txt.vim file contain any other information? Does this depend on another linux package (I'm running Ubuntu)? Many thanks in advance!

**Comment by isene** [comment]
This shouldn't depend on any other packages. It follows this VIM tip: 

   https://vim.fandom.com/wiki/Different_syntax_highlighting_within_regions_of_a_file

Try this: Have a bare bone .vimrc (empty would be good) and a txt.vim with ONLY those three lines and put the txt.vim into your .vim/syntax folder.

Report how that went :-)

**Comment by isene** [comment]
Any news on testing this?

Anyone else wants to test this feature?

Because it works just nicely here (and a few other users have this feature working).
