### ISSUE TITLE
HyperListTutorialAndTestSuite references ~/.vim directory

### ISSUE THREAD

**Issue by Jemi** [isene/hyperlist.vim#6]
HyperListTutorialAndTestSuite.hl assumes that HyperList.hl exists in ~/.vim/doc/. This is not consistent with neovim's config layout and is also not consistent with more modern (and cleaner) XDG base directory based config layouts. Hyperlist should not make assumptions about where its documentation is located, but should instead find out where it is and set a variable - something like $HLDOCDIR for example, and then this variable should be referenced instead of ~/.vim/doc. In my own use case I have set up a script to use hyperlist as a separate app with this line:

 XDG_CONFIG_HOME="${HOME}/.config/hyperlist" nvim "$@"
 
I would like nvim's directory layout to be fully supported as well as use cases like my own.

**Comment by isene** [comment]
As I am not using neovim (and prefer to continue with VIM and my elaborate setup) - would you do a PR for this and add/change the code to make it fit neovim?
