### ISSUE TITLE
Inconsistent behavior in nvim while following links

### ISSUE THREAD

**Issue by Jemi** [isene/hyperlist.vim#7]
In nvim while going through HyperListTutorialAndTestSuite.hl, using gf to follow the link <~/.vim/doc/Hyper
List.hl> will sometimes work, but usually it results in a lot of output like this: 
E10: should be followed by /, ? or &
--- Autocommands ---
line     38:
E10: \ should be followed by /, ? or &

**Comment by isene** [comment]
Would like a contribution on this one, just like with #6
