### ISSUE TITLE
HyperList Test Suite is displayed inconsistently

### ISSUE THREAD

**Issue by Jemi** [isene/hyperlist.vim#8]
Opening HyperList Test suite usually just displays the first line at first, but sometimes the display looks like this:

HyperList Test Suite (V0.99); Press '\f' to uncollapse this whole HyperList
   This HyperList serves two purposes
   Requires the files <HyperListTestSuite.hl> and <~/.vim/syntax/hyperlist.vim>
   Tests are broken into 3 major categories, "SYNTAX HIGHLIGHTING", "FUNCTIONALITY TEST" An
d "MENU TEST"
   SYNTAX HIGHLIGHTING
   FUNCTIONALITY TEST
   MENU TEST

**Comment by Jemi** [comment]
Update: I just tried with gvim and what displayed initially was just a single line as expected, but then \f did not have any effect until I went to move the cursor afterwards, whereupon the display looked as I described above (which I guess is what it looks like uncollapsed just one level throughout the whole file).

**Comment by isene** [comment]
iThis seems to be the correct behavior, then.
