### ISSUE TITLE
Can't set another text editor for opening file references

### ISSUE THREAD

**Issue by 1337M0nst3r** [isene/hyperlist.vim#9]
I use NeoVim and I want to open file references, like: &lt;file:myOtherList.hl&gt; using NeoVim instead of Vim.
However I don't see any way of doing this, I took a look at the source code and I still can't find a way to do it beside changing the code which would be overwritten on updates.

**Comment by isene** [comment]
As an immediate fix, change line 375 in syntax/hyperlist.vim (the main file) from:

`exe '!vim '.gofl`

to

`exe '!nvim '.gofl`

In the meantime, I should figure out a smooth way of handling the nvim use cases.

**Comment by 1337M0nst3r** [comment]
Maybe you could check for a EDITOR environment variable and when it doesn't exist fallback to vim, this is how most of the CLI apps do it.

**Comment by isene** [comment]
OK, do this quick test: Change line 375 to this:
`exe '!'.$EDITOR.' '.gofl`
Does that work for NeoVIM?

**Comment by 1337M0nst3r** [comment]
Sorry for the late reply, unfortunately it doesn't work, here's a screenshot so you can see it better:
![sendToGithub](https://user-images.githubusercontent.com/34712352/76783625-e7dfc000-67ba-11ea-8ad9-bf73a8642929.png)

**Comment by isene** [comment]
happy-funeral :-D
What on Earth is nwim doing here? The output looks crazy. Could you paste the output here?

**Comment by 1337M0nst3r** [comment]
```
:!nvim quickTest2.hl
^[[?1049h^[[22;0;0t^[[?1h^[=^[[H^[[2J^[]11;?^[[?2004h^[[?25hVim: Error reading input, exiting...

Vim: Finished.
^[[?25l^[(B^[[m^[[H^[[2J^[[?1004h^[[38;2;255;255;255m^[[48;2;48;48;48m^[[H^[[2J^[]112^[[2 q^[]112^[[2 q^[[?25h^[[?25l^[[23B^[[?25h^[[?25l^[]112^[[2 q^[(B^[[m^[[?25h^[[?1l^[>^[[?1049l^[[23;0;0t^[
[?2004l^[[?1004l^[[?25h
shell returned 1
Press ENTER or type command to continue
```
NeoVim probably tries to start a new NeoVim instance the same you would do in a terminal and fails.

**Comment by isene** [comment]
Ah, but you need the "exe" first. Try typing this in normal mode:

`:exe !nvim quickTest2.hl`

**Comment by 1337M0nst3r** [comment]
Sorry for the late reply again.
I tried that, it gives the same output as the previous reply.

**Comment by isene** [comment]
Sorry for the missing quotes there, did you also manually try inside neovim:
`:exe '!nvim quickTest2.hl'`
...and also making sure the file quickTest2.hl is in the directory where you launced neovim?

**Comment by 1337M0nst3r** [comment]
Yes and yes.
